### ISSUE TITLE
can you add support for SGB core and Gamate

### ISSUE THREAD

**Issue by MorkMikael** [theypsilon/Names_TXT_Updater_MiSTer#2]
hi can you add support for SGB core and Gamate
SGB: Nint. SGB
Gamate: Bit Corp. Gamate
Gamate: UMC. Gamate
best regards
Mork

**Comment by theypsilon** [comment]
As the documentation explains, this is not defined in this repository, please share it in this other one: https://github.com/ThreepwoodLeBrush/Names_MiSTer
